name: Deploy Infra

on:
  push:
    branches:
      - master

env:
  ENV_NAME: prod
  COMPOSE_FILE: infra/docker-compose.yml
  DEPLOY_DIR: ~/kodeksa-infra

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Copy docker-compose to VPS
        uses: appleboy/scp-action@v0.1.4
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          key: ${{ secrets.VPS_SSH_KEY }}
          port: 22
          source: "infra/*"
          target: ${{ env.DEPLOY_DIR }}
          strip_components: 1

      - name: Deploy PostgreSQL Infra
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          key: ${{ secrets.VPS_SSH_KEY }}
          port: 22
          script: |
            cd ${{ env.DEPLOY_DIR }}
            docker network create backnet || true
            docker-compose -p kodeksa-infra -f ${{ env.COMPOSE_FILE }} up -d
