name: Deploy Infra to VPS

on:
  push:
    branches:
      - master

jobs:
  deploy:
    name: Deploy PostgreSQL infra
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup SSH access
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.VPS_SSH_KEY }}" > ~/.ssh/id_ed25519
          chmod 600 ~/.ssh/id_ed25519
          ssh-keyscan -H ${{ secrets.VPS_HOST }} >> ~/.ssh/known_hosts

      - name: Deploy Docker Compose to VPS
        run: |
          ssh ${{ secrets.VPS_USER }}@${{ secrets.VPS_HOST }} << 'EOF'
            cd /home/kenyra/kodeksa-infra
            git pull origin master
            docker network create backnet || true
            docker-compose -p kodeksa-infra -f infra/docker-compose.yml up -d
          EOF
